購入履歴の実装
commude/vtuberland-api pull request #10
Opened 2020-09-15 09:56 UTC by akira-hosoda-commude

## やったこと

* 購入履歴のフロントを実装
* 購入履歴に使用するAPIを実装
* 購入履歴削除機能を実装

## やらないこと

* なし

## できるようになること（ユーザ目線）

* 購入履歴の確認と削除

## できなくなること（ユーザ目線）

* なし

## 動作確認

* 購入履歴の表示、検索、削除

## その他

* レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）

2020-09-15 10:44 UTC, YutaInoueCommudePH requested changes

2020-09-15 10:44 UTC, YutaInoueCommudePH commented on app/Http/Controllers/Admin/Web/PurchaseController.php
> +    }
Transaction を削除すると、レシートを削除する事になっていますので、伊藤さんと仕様書を確認します。

2020-09-15 10:44 UTC, YutaInoueCommudePH commented on app/Http/Controllers/Admin/Web/PurchaseController.php
> +                                ->orWhere('users.name', 'LIKE', "%{$search}%")
可能でしたら、ScopeTrait を使って見てください。

2020-09-15 10:44 UTC, YutaInoueCommudePH commented on app/Http/Controllers/Admin/Web/PurchaseController.php
> +                                    ->get();
SQL と Eloquent、どちらが早いか、検証可能でしょうか？

2020-09-15 10:44 UTC, YutaInoueCommudePH commented on app/Http/Controllers/Admin/Web/PurchaseController.php
> +        $purchaseList = array();
`$purchaseList = [];`

2020-09-15 10:44 UTC, YutaInoueCommudePH commented on app/Http/Controllers/Admin/Web/PurchaseController.php
> +            $purchaseList[$key] = $tmpList;
tmpList を削除して、
`$purchaseList[$key] = [.....];`
にする。

2020-09-15 10:44 UTC, YutaInoueCommudePH commented on app/Http/Resources/Bases/DataTableResource.php
> +    protected $totalPrice;
コメントの追加をお願いします。

2020-09-15 10:44 UTC, YutaInoueCommudePH commented on public/js/app.js
> +      'url': '/admin/purchaselist',
可能でしたら、何らかの方法で、route() を渡す。
blade テンプレから app.js の呼び出し前に、route() を何処で変数として、使った方がいいかと思います。

2020-09-15 10:44 UTC, YutaInoueCommudePH commented on resources/views/admin/dashboard/purchases/history.blade.php
> +    @csrf
インデント

2020-09-16 02:27 UTC, akira-hosoda-commude commented on app/Http/Controllers/Admin/Web/PurchaseController.php
> +                                ->orWhere('users.name', 'LIKE', "%{$search}%")
修正いたしました

2020-09-16 02:32 UTC, akira-hosoda-commude commented on app/Http/Controllers/Admin/Web/PurchaseController.php
> +                                    ->get();
速さまで検証していませんが、統一感を持たせるためにEloquentで実装しました。

速さはSQLの方が早いと思います。
理由は下記です。
Eloquent：SQL内でのjoinによるループ + サーバー内でのforeachによるループ（total_priceを取得するため）
SQL：SQL内でのjoinによるループのみ

2020-09-16 02:32 UTC, akira-hosoda-commude commented on app/Http/Controllers/Admin/Web/PurchaseController.php
> +        $purchaseList = array();
修正いたしました。

2020-09-16 02:32 UTC, akira-hosoda-commude commented on app/Http/Controllers/Admin/Web/PurchaseController.php
> +            $purchaseList[$key] = $tmpList;
修正いたしました

2020-09-16 02:32 UTC, akira-hosoda-commude commented on app/Http/Resources/Bases/DataTableResource.php
> +    protected $totalPrice;
修正いたしました

2020-09-16 02:47 UTC, akira-hosoda-commude commented on public/js/app.js
> +      'url': '/admin/purchaselist',
修正しました

2020-09-16 02:47 UTC, akira-hosoda-commude commented on resources/views/admin/dashboard/purchases/history.blade.php
> +    @csrf
修正しました

2020-09-16 02:59 UTC, akira-hosoda-commude commented on app/Http/Controllers/Admin/Web/PurchaseController.php
> +    }
削除機能を削除いたしました

2020-09-16 06:40 UTC, YutaInoueCommudePH commented on app/Http/Controllers/Admin/Web/PurchaseController.php
> +                "price" => $purchase->spotCharacter[0]->character->price,
`isset($purchase->spotCharacter[0]) ? $purchase->spotCharacter[0]->character->name : ''`

2020-09-16 06:44 UTC, YutaInoueCommudePH approved these changes

2020-09-16 06:44 UTC, merged