購入者リスト：API、DataTableの実装完了
commude/vtuberland-api pull request #12
Opened 2020-09-16 09:32 UTC by akira-hosoda-commude

## やったこと

* 購入者リストの実装
　API、JSの実装

## やらないこと

* なし

## できるようになること（ユーザ目線）

* 購入者リストの確認

## できなくなること（ユーザ目線）

* なし

## 動作確認

* 購入者リストの表示、検索機能の確認

## その他

* レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）

2020-09-16 09:39 UTC, YutaInoueCommudePH requested changes

2020-09-16 09:39 UTC, YutaInoueCommudePH commented on app/Http/Controllers/Admin/Web/BuyerController.php
> +        }
Laravel の collection を使ってみてください。
https://laravel.com/docs/7.x/collections

2020-09-16 09:39 UTC, YutaInoueCommudePH commented on app/Http/Controllers/Admin/Web/BuyerController.php
> +                }
こちらも、collection でお願いいたします。

2020-09-16 09:39 UTC, YutaInoueCommudePH commented on routes/admin-web.php
> +        Route::get('/show/{user}', 'BuyerController@show')->name('show');
show を外す。

2020-09-16 09:41 UTC, YutaInoueCommudePH requested changes

2020-09-16 09:41 UTC, YutaInoueCommudePH commented on routes/admin-web.php
> +        Route::get('/userlist', 'BuyerController@userList')->name('list');
/users でお願いいたします。

2020-09-17 02:53 UTC, akira-hosoda-commude commented on app/Http/Controllers/Admin/Web/BuyerController.php
> +                }
collectionのsum関数の使用を試みたのですが、テーブルの構成上、難しそうでした

2020-09-17 02:53 UTC, akira-hosoda-commude commented on routes/admin-web.php
> +        Route::get('/userlist', 'BuyerController@userList')->name('list');
修正いたしました

2020-09-17 05:04 UTC, YutaInouePH commented on app/Http/Controllers/Admin/Web/BuyerController.php
> +        }
`$priceList->each(function($price) {
    $totalPrice += $price->character->price;
})`

https://laravel.com/docs/7.x/collections

2020-09-17 06:17 UTC, YutaInoueCommudePH approved these changes

2020-09-17 06:27 UTC, merged